### ISSUE TITLE
`Error: Container action is only supported on Linux`

### ISSUE THREAD

**Issue by janpio** [Workshop64/buildpulse-action#2]
Just tried to add this action into our GH Actions pipeline (https://github.com/prisma/prisma/pull/11967), but unfortunately half of our builds run on Windows and MacOS which is not supported by the action. That is unfortunately pretty limiting for our use case (especially as I know our most flaky tests are on MacOS without Docker and I was hoping to track these).

**Comment by jasonrudolph** [comment]
👋 @janpio: Thanks for letting me know that you ran into this. I'm sorry for the friction. I'll try to help get things heading in the right direction for you.

**macOS**: The good news is that we should be able to get macOS support up and running for you pretty quickly. In fact, you can even see an [example of it in action in Homebrew/brew](https://github.com/Homebrew/brew/pull/11578/files#diff-1db27d93186e46d3b441ece35801b244db8ee144ff1405ca27a163bfe878957fR331-R333). :-) As you'll notice in that example, we're not using the GitHub Action there, since container actions are only supported on Linux. Instead, we're installing the [BuildPulse test-reporter binary](https://github.com/buildpulse/test-reporter/releases) and running it directly. (The GitHub Action is just a tiny wrapper around the test-reporter binary, so we're not really losing anything by downloading and running the test-reporter binary directly. 😅) I'll comment on https://github.com/prisma/prisma/pull/11967 to try to help get things set up. **UPDATE**: Commented at https://github.com/prisma/prisma/pull/11967#discussion_r811508926.

**Windows**: I don't yet have a test-reporter binary for Windows, but since the [test-reporter](https://github.com/buildpulse/test-reporter) is written in Go, it _should_ be possible to ship a Windows binary. I'll look into this and let you know what I find out.

**About the error:** `Container action is only supported on Linux`: I'll update the README of this action to state that the action works well for Linux, and I'll include instructions for using the test-reporter binary directly on macOS.

**Comment by jasonrudolph** [comment]
> **Windows**: I don't yet have a test-reporter binary for Windows, but since the [test-reporter](https://github.com/buildpulse/test-reporter) is written in Go, it _should_ be possible to ship a Windows binary. I'll look into this and let you know what I find out.

👋 @janpio: I've published a pre-release version of the test-reporter with support for Windows: [v0.23.0-pre](https://github.com/buildpulse/test-reporter/releases/tag/v0.23.0-pre).

I put together a [tiny demo workflow](https://github.com/buildpulse/test-reporter/blob/4ef5020279a9857708b9e2538e6df99a16185947/.github/workflows/demo.yml#L65-L89) to verify that it's working, and we can see the [successful upload when it runs](https://github.com/buildpulse/test-reporter/runs/5325647130?check_suite_focus=true#step:5:30).

(**UPDATE 2022-02-24**:  I moved the demo workflow to the `main` branch and updated the links in the above paragraph.)

You'd be the first team using the Windows binary, so we might bump into issues that we don't know about yet. If that happens, I'll certainly prioritize investigating those issues, but I just want to set expectations that we _might_ encounter some unforeseen friction. 

Would you like to try to incorporate this into https://github.com/prisma/prisma/pull/11967, or would it make sense to get https://github.com/prisma/prisma/pull/11967 shipped and then have a follow-up pull request to add Windows support? I would personally recommend adding Windows support in a follow-up pull request so that https://github.com/prisma/prisma/pull/11967 doesn't get any larger and can ship sooner, but what sounds best to you?

**Comment by jasonrudolph** [comment]
👋 @janpio: I've published a stable release of the test-reporter with preliminary support for Windows: [v0.23.0](https://github.com/buildpulse/test-reporter/releases/tag/v0.23.0). It's been working reliably in my testing, so I'm cautiously optimistic that it's ready for people to try it out. Please feel free to give it a try at your convenience, and let me know if you run into any issues or if you'd like a hand with anything. 

I've also [updated the README to include instructions for using the test-reporter binary on macOS and Windows](https://github.com/Workshop64/buildpulse-action/commit/dda8f2c5cc42a0782da83e41aae7336939041d61), so hopefully that will help future teams avoid running into the `Container action is only supported on Linux` error. 🤞 

With those things in place, I think we can close out this issue. If there's anything else that would be helpful to address, just let me know. :bow:

**Comment by janpio** [comment]
Awesome. 🪟  

The one thing that would make me fully happy and jump on adding this right now would be an example if a job that works on all 3 operating systems. Probably 3 different `run` steps gated with `if`, or some weird bash code that switches between binaries to download.

**Comment by jasonrudolph** [comment]
> The one thing that would make me fully happy and jump on adding this right now would be an example if a job that works on all 3 operating systems. Probably 3 different `run` steps gated with `if`, or some weird bash code that switches between binaries to download.

Oh yeah, that totally makes sense.

While working on the [macOS](https://github.com/buildpulse/test-reporter/blob/4ef5020279a9857708b9e2538e6df99a16185947/.github/workflows/demo.yml#L55-L63) and [Windows](https://github.com/buildpulse/test-reporter/blob/4ef5020279a9857708b9e2538e6df99a16185947/.github/workflows/demo.yml#L82-L89) examples, I found myself thinking: How can I make it so that developers don't even have to think about this stuff?

With that in mind, I want to explore converting this to a JavaScript-based action that handles all of this for you. It would figure out what platform it's running on, download the appropriate binary for that platform, and invoke the binary for you.

So, I'm going to look into that. It will probably be at least a few weeks before I can get to it, but I’ll follow up here once I give it a try.

**Comment by janpio** [comment]
Nice.

There are also "composite" actions which are weird in some ways, but could be a pretty good match (Recently interacted with one that I forked at https://github.com/janpio/azure-cosmos-db-emulator-github-action/ + https://github.com/janpio/azure-cosmos-db-emulator-github-action/blob/main/action.yml [that one is Windows only, but I would be surprised if you can not handle what you need in there])

**Comment by jasonrudolph** [comment]
Thanks so much for that pointer, @janpio! A composite action seems to do the trick (#3), and that's a much smaller change than switching to a JavaScript-based action. 😅

If you're interested, you can see the composite action in use in this [job step](https://github.com/jasonrudolph/significant-other-vscode/blob/72219ae5b3510d64b423a39f688942b595c841c5/.github/workflows/ci.yml#L40-L50), which [runs on macOS and Linux](https://github.com/jasonrudolph/significant-other-vscode/blob/72219ae5b3510d64b423a39f688942b595c841c5/.github/workflows/ci.yml#L19), and we can see successful uploads for [macOS](https://github.com/jasonrudolph/significant-other-vscode/runs/5346691463?check_suite_focus=true#step:7:59) and [Linux](https://github.com/jasonrudolph/significant-other-vscode/runs/5346691473?check_suite_focus=true#step:7:59).

If you'd like to try this out in prisma/prisma, I put together a commit at https://github.com/jasonrudolph/prisma/commit/43ffd866642781e51aeb9856581bd6b44cfa2bfd that should do the trick. You'll note that it uses the `cross-platform` branch of the action. That's because I haven't yet merged #3. I'd like to first verify that it will work correctly for you. If we can confirm that it's working correctly for you in a branch on prisma/prisma, then I'll merge #3 and publish a new release of the action.

How's that sound?
